/*
 *  This file is auto generated by oeedger8r. DO NOT EDIT.
 */
#ifndef EDGER8R_SWITCHLESS_U_H
#define EDGER8R_SWITCHLESS_U_H

#include <openenclave/host.h>
#include "switchless_args.h"
#include "thread_control.h"

OE_EXTERNC_BEGIN

oe_result_t oe_create_switchless_enclave(
    const char* path,
    oe_enclave_type_t type,
    uint32_t flags,
    const void* config,
    uint32_t config_size,
    oe_enclave_t** enclave);

void handle_ocall(
    thread_control* ptc,
    uint32_t function_id,
    uint8_t* args);

/* List of ecalls */

oe_result_t enc_sum(
    thread_control* ptc,
    int arg1,
    int arg2);

/* List of ocalls */

void host_sum(
    thread_control* ptc,
    int arg1,
    int arg2,
    int sum);

OE_EXTERNC_END

#endif // EDGER8R_SWITCHLESS_U_H
