/*
 *  This file is auto generated by oeedger8r. DO NOT EDIT.
 */
#ifndef SWITCHLESS_ARGS_H
#define SWITCHLESS_ARGS_H

#include <stdint.h>
#include <stdlib.h> /* for wchar_t */ 

#include <openenclave/bits/result.h>

typedef struct _enc_sum_args_t {
	int arg1;
	int arg2;
    oe_result_t _result;
 } enc_sum_args_t;

typedef struct _host_sum_args_t {
	int arg1;
	int arg2;
	int sum;
    oe_result_t _result;
 } host_sum_args_t;

/* trusted function ids */
enum {
    fcn_id_enc_sum = 0,
    fcn_id_trusted_call_id_max = OE_ENUM_MAX
};


/* untrusted function ids */
enum {
    fcn_id_host_sum = 0,
    fcn_id_untrusted_call_max = OE_ENUM_MAX
};


#endif // SWITCHLESS_ARGS_H
