/*
 *  This file is auto generated by oeedger8r. DO NOT EDIT.
 */
#ifndef EDGER8R_SWITCHLESS_T_H
#define EDGER8R_SWITCHLESS_T_H

#include <openenclave/enclave.h>
#include "switchless_args.h"
#include "thread_control.h"

OE_EXTERNC_BEGIN

/* List of ecalls */

void handle_ecall(
    thread_control* ptc,
    uint32_t function_id,
    uint8_t* args);

void enc_sum(
    thread_control* ptc,
    int arg1,
    int arg2);

/* List of ocalls */

//oe_result_t host_sum(
//    int arg1,
//    int arg2,
//    int sum);

oe_result_t host_sum(
    thread_control* ptc,
    int arg1,
    int arg2,
    int sum);

OE_EXTERNC_END

#endif // EDGER8R_SWITCHLESS_T_H
